
image:
  file: .gitpod.Dockerfile
ports:
- port: 8080
tasks:
- command: echo "openIn left"
  openIn: left
- command: echo "openIn bottom"
  openIn: bottom
- command: echo "openIn right"
  openIn: right
- command: echo "openIn main"
  openIn: main
- command: echo "Tab 1, first"
- command: echo "Tab 1, third"
  openMode: split-right
- command: echo "Tab 1, second"
  openMode: split-left
- command: echo "Tab 2, first"
  openMode: tab-after
- command: echo "Tab 2, second"
  openMode: split-right

vscode:
  extensions:
    - lightyen.tailwindcss-intellisense-twin
    - scala-lang.scala
