
image:
  file: .gitpod.Dockerfile
ports:
- port: 8080
tasks:
- command: echo "openIn left"
  openIn: left
- command: echo "openIn bottom"
  openIn: bottom
- command: echo "openIn right"
  openIn: right
- command: echo "openIn main"
  openIn: main
- command: echo "Tab 1, first"
- command: echo "Tab 1, third"
  openMode: split-right
- command: echo "Tab 1, second"
  openMode: split-left
- command: echo "Tab 2, first"
  openMode: tab-after
- command: echo "Tab 2, second"
  openMode: split-right

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true

vscode:
  extensions:
    - lightyen.tailwindcss-intellisense-twin
    - scala-lang.scala
